/**
 * TestConstant.h
 * 
 * Copyright 2G Robotics Inc. 2021
 * 
 * This class is generated by cmake and allows the test code to find the test data.
 */

#pragma once

#include <string>

namespace tg {
namespace tags {

class TagsTestCommon {
public:

    static std::string testDataDir() {
        return std::string("${PROJECT_SOURCE_DIR}/test_data/");
    };

    static std::string testJpgNon2g() {
        return testDataDir() + "gps_info.jpg";
    };

    static std::string testTifNon2g() {
        return testDataDir() + "exif.tif";
    };

};

} //tags
} //tg