[package]
name = "exif_2g"
version = "0.1.0"
authors = ["Ryan Wicks <ryancwicks@gmail.com>"]
edition = "2018"

[dependencies]
kamadak-exif = "0.5.3"
clap = {version = "2.33.3", optional=true}  

[features]
build-binary = ["clap"]

[[bin]]
name="parse_tags"
required-features=["build-binary"]
